### ISSUE TITLE
I can get this key but it has no effect 

### ISSUE THREAD

**Issue by wc410514046** [tomer8007/widevine-l3-decryptor#11]
https://v.youku.com/v_show/id_XNDcxOTQ5ODMxNg==.html?spm=a2hbt.13141534.app.5~5!2~5!2~5~5~5!2~5~5!2~5!2~5!2~5~A!6&s=adbb85b0280346f29299
![image](https://user-images.githubusercontent.com/62002889/97068108-1fd39f00-15f7-11eb-9189-0da179770e4e.png)
I concat the video by init and 01 02 03. . . . . .
![image](https://user-images.githubusercontent.com/62002889/97068130-56111e80-15f7-11eb-999d-a977ff2e5b19.png)
and Ran the command
ffmpeg.exe -decryption_key 83ec2fb2028ac486bf491dcf7caaf33c  -i ao.mp4 -codec copy a11n.mp4
but error
![image](https://user-images.githubusercontent.com/62002889/97068217-4c3beb00-15f8-11eb-8f7a-f472cc377e6b.png)
 can you help me see it?

**Comment by wc410514046** [comment]
![微信图片_20201024125847](https://user-images.githubusercontent.com/62002889/97068271-beaccb00-15f8-11eb-8705-a4326db18c23.png)
![微信图片_20201024125845](https://user-images.githubusercontent.com/62002889/97068275-c0768e80-15f8-11eb-9f5e-80470bc15505.png)

![微信图片_20201024125805](https://user-images.githubusercontent.com/62002889/97068273-bfddf800-15f8-11eb-85cc-a4efd3b3eb4b.png)

**Comment by zackmark29** [comment]
Use MP4Decrpyt.

mp4decrypt.exe --keyKID:KEY input.mp4 output.mp4

(e.g.) mp4decrypt.exe --key 3fa132ccf22a44799ca5e145c2850a8d:b81d4f73cab20142d3ec50610338ce30 encrypted.mp4 decrypted.mp4

**Comment by plmxs2017** [comment]
> https://v.youku.com/v_show/id_XNDcxOTQ5ODMxNg==.html?spm=a2hbt.13141534.app.5~5!2~5!2~5~5~5!2~5~5!2~5!2~5!2~5~A!6&s=adbb85b0280346f29299
> ![image](https://user-images.githubusercontent.com/62002889/97068108-1fd39f00-15f7-11eb-9189-0da179770e4e.png)
> I concat the video by init and 01 02 03. . . . . .
> ![image](https://user-images.githubusercontent.com/62002889/97068130-56111e80-15f7-11eb-999d-a977ff2e5b19.png)
> and Ran the command
> ffmpeg.exe -decryption_key 83ec2fb2028ac486bf491dcf7caaf33c -i ao.mp4 -codec copy a11n.mp4
> but error
> ![image](https://user-images.githubusercontent.com/62002889/97068217-4c3beb00-15f8-11eb-8f7a-f472cc377e6b.png)
> can you help me see it?

How did you download this encrypted video?
