### ISSUE TITLE
Can't decrypt

### ISSUE THREAD

**Issue by C0ldF** [tomer8007/widevine-l3-decryptor#16]
Hi, in one website the plugin can't decrypt the key, appears this message:

https://img.techpowerup.org/201028/screenshot-6.png

embed.js:6 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior.

drm_engine.js:880 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior.
﻿

The MPD from file is generated with shaka packager

Generated with https://github.com/google/shaka-packager version v2.3.0-5bf8ad5-release
​

**Comment by tomer8007** [comment]
This warning is because whoever uses the EME API does not specify robustness level, it shouldn't affect the decryption.
Is it possible that a0b47ff81fedc51ef0652d1dacd96ed318ce7e63 fixes your issue?

**Comment by C0ldF** [comment]
Thanks sir, its working now.
