### ISSUE TITLE
CryptoJS.CMAC Error

### ISSUE THREAD

**Issue by stinkteeth** [tomer8007/widevine-l3-decryptor#17]
I tested this extension in a particular instance some 5 days ago and it functioned properly.  Now, use of the extension in the very same instance (in all respects) results in the following error:
Uncaught (in promise) TypeError: CryptoJS.CMAC is not a function at Object.WidevineCrypto.decryptContentKey

What sort of error is this?

Edit: Looks like they changed some of the field data descriptors in the license response:
Message SignedLicense.Msg is missing required fields: Key[1]._KeyControl.Iv

Edit: Never mind, silly issue.  Closing.

**Comment by stinkteeth** [comment]
Sorry, silly issue.  Closing.

**Comment by vikralthakur** [comment]
> Sorry, silly issue. Closing.

Hello, I also got the same `TypeError` did you have any way to fix it?
