### ISSUE TITLE
How can i download the main video from this details??

### ISSUE THREAD

**Issue by tvserial** [tomer8007/widevine-l3-decryptor#20]
{
    "link": "https://mediacloudfront.zee5.com/drm1/elemental/dash/ON_AIR/DOMESTIC/ZEE_BANGLA/October2020/29102020/Seamless/Ki_Kore_Bolbo_Tomay_Ep183_Seamless_29102020_bn_d4f06505f615a10ab86b9054811fb9df/manifest.mpd",
    "lic":  key=f6b23130-c941-4153-a862-2479620a2666&id=0-1-manual_7t616ur1e0n0"
}

**Comment by spacex97** [comment]
why you are going for MPD when you can download for free through HLS huh

**Comment by tvserial** [comment]
hls cant download it..because it has drm ...its drm protected content

**Comment by spacex97** [comment]
like i said people really like to waste time on such silly things, drm free link is as below.
`https://zee5vodnd.akamaized.net/hls1/elemental/hls/ON_AIR/DOMESTIC/ZEE_BANGLA/October2020/29102020/Seamless/Ki_Kore_Bolbo_Tomay_Ep183_Seamless_29102020_bn_d4f06505f615a10ab86b9054811fb9df/index.m3u8?hdnea=st=1604082664~exp=1604085664~acl=/*~hmac=112b6e3d09d7ca39ab0db8645690961c0906d9498f2f346c8b1d294116917d5c`

**Comment by tvserial** [comment]
this is free after publishing tv...before tv published its drm
protected...firstly published it ott platform ....& how i find easily free
link??can you help me?

**Comment by tvserial** [comment]
can you tell me(? where i get those type free link? or extract main url
from manifest.mpd file
