### ISSUE TITLE
How can i download the main video from this details??

### ISSUE THREAD

**Issue by tvserial** [tomer8007/widevine-l3-decryptor#22]
{
"link": "https://mediacloudfront.zee5.com/drm1/elemental/dash/ON_AIR/DOMESTIC/ZEE_BANGLA/October2020/29102020/Seamless/Ki_Kore_Bolbo_Tomay_Ep183_Seamless_29102020_bn_d4f06505f615a10ab86b9054811fb9df/manifest.mpd",
"lic": key=f6b23130-c941-4153-a862-2479620a2666&id=0-1-manual_7t616ur1e0n0"
}

**Comment by lekoOwO** [comment]
STOP SPAMMING
Downloading mpd is easy af. If you even can't google for it, Github is not your place.

Answer is at the first page of google search, wuts wrong w/ you?

**Comment by tvserial** [comment]
youtube dl cant Download it..thats why i want help..i dont make any sspam
post

**Comment by tvserial** [comment]
https://mediacloudfront.zee5.com/drm1/elemental/dash/TV_SHOWS/ZEE_TV/October2020/31102020/Seamless/Kundali_Bhagya_CS_Ep806_Seamless_31102020_hi_55a6e685dcc345f7cd5dccc8121c76da/manifest.mpd

i try this many ways.. vlc 1kb after download....youtube dl cant download because of drm.......please someone help..its my humble request..
