### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by tvserial** [tomer8007/widevine-l3-decryptor#23]
{
    "link": "https://mediacloudfront.zee5.com/drm1/elemental/dash/ON_AIR/DOMESTIC/ZEE_BANGLA/November2020/02112020/Seamless/Ki_Kore_Bolbo_Tomay_Ep185_Seamless_02112020_bn_3ece9bfd5fc7bcc8e9d459cced957639/manifest.mpd",
    "lic": "http://devtv.pro/movies/zee5/lic.php?key=38db35b0-7146-49b8-886b-a5d1b1e70b71&id=0-1-manual_5h9ifc0p77n0"
}

how can i download main video? or playing?

**Comment by quickstreamingmedia** [comment]
I can help you contact on telegram @alienmaster9
