### ISSUE TITLE
BRO PLS GIVE AGAIN I WANT TO DOWNLOAD THIS

### ISSUE THREAD

**Issue by Kapc779** [tomer8007/widevine-l3-decryptor#27]
PLEASE GIVE AGAIN DONT REMOVE IT

**Comment by Hidend** [comment]
https://github.com/tomer8007/widevine-l3-decryptor/tree/ed8a97745c69b8cc0fc7f59cec9474b216b49e16

**Comment by sahilkundu** [comment]
BRO THIS EXTENSION GIVE AN ERROR LIKE THAT " **
![screenshot](https://user-images.githubusercontent.com/71582663/113404546-f26cf780-93c5-11eb-9964-b368f10c0897.png)
**It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior** " PLEASE SOLVE AND GIVE ME ANY RESPONSE .

**Comment by sahilkundu** [comment]
Bro This give me an error like that ( in a screenshot ) please give any solution .
![screenshot](https://user-images.githubusercontent.com/71582663/113404917-95be0c80-93c6-11eb-956d-2789dd5bb8cb.png)
