### ISSUE TITLE
ffmpeg -decryption_key not working

### ISSUE THREAD

**Issue by leodomi** [tomer8007/widevine-l3-decryptor#28]
Hi, I cant' find a ffmpeg build that supports the `-decryption_key` option.

![image](https://user-images.githubusercontent.com/33042520/99947336-22e9b880-2d78-11eb-85ee-257d7baa1147.png)

Could you tell me how to get it working pls ?

**Comment by beta2k** [comment]
use mp4decrypt instead: https://www.bento4.com/documentation/mp4decrypt/
