### ISSUE TITLE
Share research?

### ISSUE THREAD

**Issue by Anan5a** [tomer8007/widevine-l3-decryptor#30]
I would like to try reversing the Linux library's private key, Would you like to share the research for reversing the windows dll? 
For example methods used for detecting the code containing key, de obfuscation process etc...

**Comment by devporter007** [comment]
Here are some resources that might help you. 

Key is obtained via applying DFA on AES 

[](https://www.blackhat.com/docs/eu-15/materials/eu-15-Sanfelix-Unboxing-The-White-Box-Practical-Attacks-Against-Obfuscated-Ciphers-wp.pdf)

[](https://www.researchgate.net/profile/Christophe_Giraud/publication/221005703_DFA_on_AES/links/00b7d52c1f13e36ef1000000/DFA-on-AES.pdf?origin=publication_detail)
