### ISSUE TITLE
Need help in downloading Video

### ISSUE THREAD

**Issue by ssrikanth3252** [tomer8007/widevine-l3-decryptor#32]
When i try to access the url "https://bitmovin.com/demos/drm"

in the network tab i am seeing the below Url

https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/mpds/11331.mpd

In the console the below text is displayed

Found key: 100b6c20940f779a4589152b57d2dacb (KID=eb676abbcb345e96bbcf616630f1a3da)
 Found key: 3bda2f40344c7def614227b9c0f03e26 (KID=0294b9599d755de2bbf0fdca3fa5eab7)
Found key: 229f5f29b643e203004b30c4eaf348f4 (KID=639da80cf23b55f3b8cab3f64cfa5df6)

I installed FFMPEG and try to execute the below command "ffmpeg -decryption_key 100b6c20940f779a4589152b57d2dacb -i encrypted_media.mp4 -codec copy decrypted_media.mp4"

but i am not sure how encrypted_media.mp4 & decrypted_media.mp4 will be generated and should i replace '-codec' with anyother thing?

I don't have technical knowledge about this.Can you please elaborate how i can download the video specified at https://bitmovin.com/demos/drm?

**Comment by karapuz007** [comment]
https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd

**Comment by tvserial** [comment]
How can i download &Join the init segment with all other segments then decrypt using it??.please help

**Comment by tvserial** [comment]
tomer8007 please help...reply..

**Comment by tomer8007** [comment]
This is not the right place to discuss downloding videos, you have reddit for that.

**Comment by moonmuaaz000** [comment]
https://forum.videohelp.com/threads/400863-Downloading-encrypted-mpd-video-files
