### ISSUE TITLE
Uncaught (in promise) TypeError: CryptoJS.CMAC is not a function

### ISSUE THREAD

**Issue by ilysnemo** [tomer8007/widevine-l3-decryptor#34]
![image](https://user-images.githubusercontent.com/58479574/104057454-c574d280-5224-11eb-9686-c83fdc7bf60e.png)

I got this error when open video from hulu. How i can fix it? anyone pls help me~
Thank you

**Comment by Sipherdrakon** [comment]
Did you figure it out or no?
