### ISSUE TITLE
Can't Decrypt 

### ISSUE THREAD

**Issue by jverav** [tomer8007/widevine-l3-decryptor#36]
HI, I have a problem with a page , the plugin can't decrypt the key, this is the error .

https://imgur.com/OuGBukX - Console
https://imgur.com/Yxq6jay - Sources

Thaks for your time and for this plugin.

**Comment by tvserial** [comment]
How can i download &Join the init segment with all other segments then decrypt using it??.please help

**Comment by Jon171** [comment]
> How can i download &Join the init segment with all other segments then decrypt using it??.please help

Use JDownloader to copy the links. Join them all into one package, rename each file to ensure they're in the sequential order, combine them together using "copy /b init.mp4 + *.m4s (or whatever extension they use) "output file". Then when your stream is compiled make sure you downloaded mp4decrypt.exe, open command prompt in the same directory, then run "mp4decrypt --key kid:key "sourcevideotitle.mp4" "exportedvideotitle.mp4".
