### ISSUE TITLE
i cant join segemnt video or cant downloadencrypted video..

### ISSUE THREAD

**Issue by tvserial** [tomer8007/widevine-l3-decryptor#37]
How can i Join the init segment with all other segments then decrypt using ??.please help

**Comment by moonmuaaz000** [comment]
use N_m3u8-cli

**Comment by tvserial** [comment]
bro its mpd files...& drm protected it is..i acnt download it...i have kid & key...but need to download first then i can decrypt it

**Comment by HackerBoy0412** [comment]
N_M3U8DL-CLI is possible and wich site?

**Comment by tvserial** [comment]
hotstar.com.   i give mpd url..access denied showing

**Comment by yolanda123a** [comment]
same problem for me, in hbo go latam i have a mpd file and i dont know how download
and dash proxy dosent work any more
