### ISSUE TITLE
Latest Chrome dont work

### ISSUE THREAD

**Issue by HackerBoy0412** [tomer8007/widevine-l3-decryptor#39]
With the latest Chrome Update the plugin dont work.
Can it please get updated?

**Comment by tomer8007** [comment]
Sorry, a new key will not be published (this is just getting into a cat-and-mouse game).

**Comment by tomer8007** [comment]
Yes

**Comment by Felicia208** [comment]
> Sorry, a new key will not be published (this is just getting into a cat-and-mouse game).
> 
> If you really want a workaround, though, you can just replace your `widevinecdm.dll` and `widevinecdm.dll.sig` files with the older versions.

I am sorry but could I ask how to obtain the old version of `widevinecdm.dll` and `widevinecdm.dll.sig` files? I didn't know I should keep those files and Chrome just updated so I can't find the old version of them.

**Comment by Felicia208** [comment]
> > Sorry, a new key will not be published (this is just getting into a cat-and-mouse game).
> > If you really want a workaround, though, you can just replace your `widevinecdm.dll` and `widevinecdm.dll.sig` files with the older versions.
> 
> I am sorry but could I ask how to obtain the old version of `widevinecdm.dll` and `widevinecdm.dll.sig` files? I didn't know I should keep those files and Chrome just updated so I can't find the old version of them.

Solved. Thanks for the solution.

**Comment by Suyashjain05** [comment]
hey , where did you find widevinecdm.dll.sig file ?
i can find only widevinecdm.dll older versions .
Kindly help

**Comment by Felicia208** [comment]
> hey , where did you find widevinecdm.dll.sig file ?
> i can find only widevinecdm.dll older versions .
> Kindly help

I actually use the ones from Microsoft Edge browser folder. Edge hasn't been updated yet so the widevinecdm.dll and widevinecdm.dll.sig are still in old version.

**Comment by Suyashjain05** [comment]
oh thank you 


> > hey , where did you find widevinecdm.dll.sig file ?
> > i can find only widevinecdm.dll older versions .
> > Kindly help
> 
> I actually use the ones from Microsoft Edge browser folder. Edge hasn't been updated yet so the widevinecdm.dll and widevinecdm.dll.sig are still in old version.

oh great
thanks

**Comment by etnaddcok** [comment]
unfortunately it no longer works

**Comment by sahilkundu** [comment]
> > > Sorry, a new key will not be published (this is just getting into a cat-and-mouse game).
> > > If you really want a workaround, though, you can just replace your `widevinecdm.dll` and `widevinecdm.dll.sig` files with the older versions.
> > 
> > 
> > I am sorry but could I ask how to obtain the old version of `widevinecdm.dll` and `widevinecdm.dll.sig` files? I didn't know I should keep those files and Chrome just updated so I can't find the old version of them.
> 
> Solved. Thanks for the solution.

Please tell me also friend. I want to know this because i don't know also .

**Comment by sahilkundu** [comment]
How can be download widevinecdm.dll and widevinecdm.dll.sig of older version please tell i have not founder.
If anyone have this , send me this please frnds.

**Comment by Flam3rboy** [comment]
found it download the latest version: 4.10.1610.0
https://www.dll-files.com/widevinecdm.dll.html

**Comment by Flam3rboy** [comment]
or just use a older chrome version, e.g.
https://www.heise.de/download/product/google-chrome-portable-57619

**Comment by abderrahmanesaad** [comment]
[sd.zip](https://github.com/tomer8007/widevine-l3-decryptor/files/6480210/sd.zip)
here are old versoin of widevinecdm.dll and widevinecdm.dll.sig

**Comment by mirrorx2** [comment]
> [sd.zip](https://github.com/tomer8007/widevine-l3-decryptor/files/6480210/sd.zip)
> here are old versoin of widevinecdm.dll and widevinecdm.dll.sig



> Sorry, a new key will not be published (this is just getting into a cat-and-mouse game).
> 
> If you really want a workaround, though, you can just replace your `widevinecdm.dll` and `widevinecdm.dll.sig` files with the older versions.

I have a site which I want to take a video.....The extension worked fine until yersterday...I used chrome version 87. But today widewine decrypter doesn't decrypter didn't capture the keys and chrome version hasn;t been updated too.... I tried many old versions older than version 87 today but none of it worked! Then when I again switched to version 87 there comes a message when playing the videos saying "update your windows to latest version"... I tried replacing widevinecdm.dll and widevinecdm.dll.sig with older versions too but none of it worked...

What I have to ask is if you know any other way to get the keys please help me...I really need some videos...They are lesson videos and I really need to get them before they expire😭... If anyone here read this have solution please can you be kind and share it 🙏 Thank you.

**Comment by mirrorx2** [comment]
> Sorry, a new key will not be published (this is just getting into a cat-and-mouse game).
> 
> If you really want a workaround, though, you can just replace your `widevinecdm.dll` and `widevinecdm.dll.sig` files with the older versions.

> [sd.zip](https://github.com/tomer8007/widevine-l3-decryptor/files/6480210/sd.zip)
> here are old versoin of widevinecdm.dll and widevinecdm.dll.sig



> Sorry, a new key will not be published (this is just getting into a cat-and-mouse game).
> 
> If you really want a workaround, though, you can just replace your `widevinecdm.dll` and `widevinecdm.dll.sig` files with the older versions.

I have a site which I want to take a video.....The extension worked fine until yesterday...I used chrome version 87. But today widevine decrypter didn't capture the keys and chrome version hasn't been updated too.... I tried many old versions older than version 87 today but none of it worked! Then when I again switched to version 87 there comes a message when playing the videos saying "update your windows to latest version"... I tried replacing widevinecdm.dll and widevinecdm.dll.sig with older versions too but none of it worked...

What I have to ask is if you know any other way to get the keys please help me...I really need some videos...They are lesson videos and I really need to get them before they expire😭... Also I can give you a link if anyone wants to try....If anyone here who  read this have solution please can you be kind and share it 🙏 Thank you.
