### ISSUE TITLE
Can't verify license request signature; either the platform is wrong or the key has changed!

### ISSUE THREAD

**Issue by p2mgrup** [tomer8007/widevine-l3-decryptor#40]
Hello,
How we can resolve this problem.
Today was worked in Chrome / Windows 7, but right now in all materials i have a problem.
In firefox is working good.
Are you able to help me?

**Comment by tomer8007** [comment]
This is the same issue as #39.

**Comment by p2mgrup** [comment]
Ok but i dont have this files from previous version.
Is it possible to restore those files from somewhere?

**Comment by mirrorx2** [comment]
> Hello,
> How we can resolve this problem.
> Today was worked in Chrome / Windows 7, but right now in all materials i have a problem.
> In firefox is working good.
> Are you able to help me?

> [sd.zip](https://github.com/tomer8007/widevine-l3-decryptor/files/6480210/sd.zip)
> here are old versoin of widevinecdm.dll and widevinecdm.dll.sig



> Sorry, a new key will not be published (this is just getting into a cat-and-mouse game).
> 
> If you really want a workaround, though, you can just replace your `widevinecdm.dll` and `widevinecdm.dll.sig` files with the older versions.

I have a site which I want to take a video.....The extension worked fine until yesterday...I used chrome version 87. But today widevine decrypter didn't capture the keys and chrome version hasn't been updated too.... I tried many old versions older than version 87 today but none of it worked! Then when I again switched to version 87 there comes a message when playing the videos saying "update your windows to latest version"... I tried replacing widevinecdm.dll and widevinecdm.dll.sig with older versions too but none of it worked...

What I have to ask is if you know any other way to get the keys please help me...I really need some videos...They are lesson videos and I really need to get them before they expire😭... Also I can give you a link if anyone wants to try....If anyone here who  read this have solution please can you be kind and share it 🙏 Thank you.

**Comment by mirrorx2** [comment]
> This is the same issue as #39.

> [sd.zip](https://github.com/tomer8007/widevine-l3-decryptor/files/6480210/sd.zip)
> here are old versoin of widevinecdm.dll and widevinecdm.dll.sig



> Sorry, a new key will not be published (this is just getting into a cat-and-mouse game).
> 
> If you really want a workaround, though, you can just replace your `widevinecdm.dll` and `widevinecdm.dll.sig` files with the older versions.

I have a site which I want to take a video.....The extension worked fine until yesterday...I used chrome version 87. But today widevine decrypter didn't capture the keys and chrome version hasn't been updated too.... I tried many old versions older than version 87 today but none of it worked! Then when I again switched to version 87 there comes a message when playing the videos saying "update your windows to latest version"... I tried replacing widevinecdm.dll and widevinecdm.dll.sig with older versions too but none of it worked...

What I have to ask is if you know any other way to get the keys please help me...I really need some videos...They are lesson videos and I really need to get them before they expire😭... Also I can give you a link if anyone wants to try....If anyone here who  read this have solution please can you be kind and share it 🙏 Thank you.
