### ISSUE TITLE
Hey, this isn't really issue. Just curious

### ISSUE THREAD

**Issue by Suyashjain05** [tomer8007/widevine-l3-decryptor#41]
So recently i found out that the extension ain't working anymore, as i can resolve from older issues , it's gotta do something with either chrome's new update or windows. So i was just curious about how can i find new keys instead of rolling back. I'd really appreciate if you'd draft that write up you were talking about.
Thank You

**Comment by tomer8007** [comment]
For things that are not really an issue please you the [Discussions page](https://github.com/tomer8007/widevine-l3-decryptor/discussions).
