### ISSUE TITLE
tutorial use

### ISSUE THREAD

**Issue by yolanda123a** [tomer8007/widevine-l3-decryptor#43]
install chrome 88 version
open for example a netflix hbo max amazon usa movie
start to playback
press F12
and go to console
there you will get the key for decrypt the movie that you are playback

and after use mp4decrypt comand for decrypt the movie
if you want any question PM i am a caring person willing to help, not like the people in this forum who are all soretes children of a mother who swallows semen with AIDS

**Comment by yolanda123a** [comment]
they dont want reveal the true use of this plugin and now all people know
i you want i can make tutorial   in youtube or another platafform

**Comment by HawkLiking** [comment]
There already are a ton of reddit post talking about that, everyone already know how to use it, nothing new here.
@tomer8007 please close
