### ISSUE TITLE
tutorial use

### ISSUE THREAD

**Issue by yolanda123a** [tomer8007/widevine-l3-decryptor#46]
this plugin is used to download drm content
this is a tutorial use how use this plugin

first you need this tools
1) Bento4-SDK-1-6-0-637.x86_64-microsoft-win32
2) plugin Widevine L3 Decryptor
3) N_m3u8DL-CLI_v2.9.6_with_ffmpeg_and_SimpleG

steps 
1) install Widevine L3 Decryptor in chrome 88 (dont work in more recent) or microsoft edge
just install the extension folder 
2) open your video that you want get
for example a movie in HBO MAX usa
3) after start  playback press f12 in your browser
go to console tab and there you will get 3 keys for decrypt the encrypted files
and go to network
and for HBO MAX search for mpd
copy url and paste in 
N_m3u8DL-CLI_v2.9.6_with_ffmpeg_and_SimpleG
4) now select the resolution video or quality audio that you need
enter and start to download
5) after copy the video and rename for example
hbomaxvideo.mp4
and go to folder 
Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\bin
paste there and open a console tab in there
and in there copy this

mp4decrypt.exe --key 1:9c97a0eaed18f201c4386d3a04d57ed4 --show-progress hbomaxvideo.mp4 c:\Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\bin\video_decrypted.mp4

(the extension can to vary)

the 
9c97a0eaed18f201c4386d3a04d57ed4

is the key that you obtain in widevine
you have to will test one key is for audio another for video and another to subtitule

6) enjoy video and audio without encrypt

**Comment by Superhackman** [comment]
could you explain for apple music either to download music or an MV

**Comment by Superhackman** [comment]
please help with https://ver.flixole.com/watch/4b580231-5171-4550-8047-6d06b964e719 not generate key

**Comment by Superhackman** [comment]
I already generate a key but it does not work, the file is still encrypted, any suggestions?

**Comment by mirrorx2** [comment]
I have a site which I want to take a video.....Your method worked fine until yesterday...I used chrome version 87. But today widevine decrypter didn't capture the keys and chrome version hasn't been updated too.... I tried many old versions older than version 87 today but none of it worked! Then when I again switched to version 87 there comes a message when playing the videos saying "update your windows to latest version"... I tried replacing widevinecdm.dll and widevinecdm.dll.sig with older versions too but none of it worked...What I have to ask is if you know any other way to get the keys please help me...I really need some videos...They are lesson videos and I really need to get them before they expire😭....If I give a link can you try... If anyone here read this have solution please can you be kind and share it 🙏 Thank you.

> this plugin is used to download drm content
> this is a tutorial use how use this plugin
> 
> first you need this tools
> 
> 1. Bento4-SDK-1-6-0-637.x86_64-microsoft-win32
> 2. plugin Widevine L3 Decryptor
> 3. N_m3u8DL-CLI_v2.9.6_with_ffmpeg_and_SimpleG
> 
> steps
> 
> 1. install Widevine L3 Decryptor in chrome 88 (dont work in more recent) or microsoft edge
>    just install the extension folder
> 2. open your video that you want get
>    for example a movie in HBO MAX usa
> 3. after start  playback press f12 in your browser
>    go to console tab and there you will get 3 keys for decrypt the encrypted files
>    and go to network
>    and for HBO MAX search for mpd
>    copy url and paste in
>    N_m3u8DL-CLI_v2.9.6_with_ffmpeg_and_SimpleG
> 4. now select the resolution video or quality audio that you need
>    enter and start to download
> 5. after copy the video and rename for example
>    hbomaxvideo.mp4
>    and go to folder
>    Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\bin
>    paste there and open a console tab in there
>    and in there copy this
> 
> mp4decrypt.exe --key 1:9c97a0eaed18f201c4386d3a04d57ed4 --show-progress hbomaxvideo.mp4 c:\Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\bin\video_decrypted.mp4
> 
> (the extension can to vary)
> 
> the
> 9c97a0eaed18f201c4386d3a04d57ed4
> 
> is the key that you obtain in widevine
> you have to will test one key is for audio another for video and another to subtitule
> 
> 1. enjoy video and audio without encrypt
I have a site which I want to take a video.....The extension worked fine until yesterday...I used chrome version 87. But today widevine decrypter didn't capture the keys and chrome version hasn't been updated too.... I tried many old versions older than version 87 today but none of it worked! Then when I again switched to version 87 there comes a message when playing the videos saying "update your windows to latest version"... I tried replacing widevinecdm.dll and widevinecdm.dll.sig with older versions too but none of it worked...

What I have to ask is if you know any other way to get the keys please help me...I really need some videos...They are lesson videos and I really need to get them before they expiresob... Also I can give you a link if anyone wants to try....If anyone here who read this have solution please can you be kind and share it pray Thank you.
