### ISSUE TITLE
Error "It is recommended that a robustness level be specified"

### ISSUE THREAD

**Issue by Suyashjain05** [tomer8007/widevine-l3-decryptor#50]
I'm getting this warning 

`It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior.`

![image](https://user-images.githubusercontent.com/53927129/112961429-fbaa5a00-9162-11eb-9e83-05df7a91e945.png)

I was wondering if there is any way around to fix this.

Thank you

**Comment by Suyashjain05** [comment]
This warning didn't used to come earlier

**Comment by tomer8007** [comment]
This warning is related to the website that uses EME, and it pretty much [means what is says](https://www.w3.org/TR/encrypted-media/#dom-mediakeysystemmediacapability-robustness). I don't think this is something to worry about as long as the media plays anyway.

**Comment by Suyashjain05** [comment]
Well, the keys aren't showing, that's the problem and the only output given by the extension is this warning, there's no key decrypted. 😅

**Comment by tomer8007** [comment]
I tried to silence this warning before in `addRobustnessLevelIfNeeded` (eme_interception.js), but I don't think it should matter too much. You can try to debug it to see if you get license requests or respones.

**Comment by tvserial** [comment]
I have a question about this..When i going sonyliv .com drm videos for playing key not showing...but fews days ago its showing...But Not showing now..What the issue??(Also mention that hbo,netflix,disney,hotstar working still...only not working for me sonyliv.com)

**Comment by Suyashjain05** [comment]
> I tried to silence this warning before in `addRobustnessLevelIfNeeded` (eme_interception.js), but I don't think it should matter too much. You can try to debug it to see if you get license requests or respones.

Well i can see the license request and response but seems like the extension doesn't see it as it stops with this warning.

**Not sure if this happens in JS**

**Comment by Suyashjain05** [comment]
> I tried to silence this warning before in `addRobustnessLevelIfNeeded` (eme_interception.js), but I don't think it should matter too much. You can try to debug it to see if you get license requests or respones.

also i don't think "addRobustnessLevelIfNeeded" function would be executed as i can see, this warning pops up from line 348 itself, therefore i think it won't execute the rest of the code below .

Note: "addRobustnessLevelIfNeeded" Function is located in line 391

**Comment by tvserial** [comment]
Object
DevTools failed to load SourceMap: Could not load content for https://www.sonyliv.com/CatchMedia/CMSDK.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
video-player.component.min.js?ver=3.2.60:3 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior.
drmSupport @ video-player.component.min.js?ver=3.2.60:3
(anonymous) @ video-player.component.min.js?ver=3.2.60:3
timnasa-obtains-new-power-1000113161?watch=true:256 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ timnasa-obtains-new-power-1000113161?watch=true:256
(anonymous) @ timnasa-obtains-new-power-1000113161?watch=true:256
(anonymous) @ timnasa-obtains-new-power-1000113161?watch=true:256
[Violation] Forced reflow while executing JavaScript took 57ms
timnasa-obtains-new-power-1000113161?watch=true:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
[Violation] 'setTimeout' handler took 370ms
The script has an unsupported MIME type ('text/html').
The FetchEvent for "https://www.sonyliv.com/" resulted in a network error response: an object that was not a Response was passed to respondWith().
Promise.then (async)
(anonymous) @ service-worker.js:75
timnasa-obtains-new-power-1000113161?watch=true:1 Site cannot be installed: Page does not work offline. Starting in Chrome 93, the installability criteria is changing, and this site will not be installable. See https://goo.gle/improved-pwa-offline-detection for more information.
The script has an unsupported MIME type ('text/html').
bundle.633ffe6e.js:1 Uncaught (in promise) TypeError: e.url.startsWith is not a function
    at bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
Promise.then (async)
p @ bundle.633ffe6e.js:1
i @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
(anonymous) @ vendors~main.55ed33fb.chunk.js:2
fetchPriceConsentTray @ App.a0f152eb.chunk.js:1
(anonymous) @ App.a0f152eb.chunk.js:1
Promise.then (async)
value @ App.a0f152eb.chunk.js:1
(anonymous) @ App.a0f152eb.chunk.js:1
Promise.then (async)
(anonymous) @ App.a0f152eb.chunk.js:1
Promise.then (async)
value @ App.a0f152eb.chunk.js:1
value @ App.a0f152eb.chunk.js:1
cs @ vendors~main.55ed33fb.chunk.js:2
Tu @ vendors~main.55ed33fb.chunk.js:2
t.unstable_runWithPriority @ vendors~main.55ed33fb.chunk.js:2
qo @ vendors~main.55ed33fb.chunk.js:2
bu @ vendors~main.55ed33fb.chunk.js:2
su @ vendors~main.55ed33fb.chunk.js:2
nu @ vendors~main.55ed33fb.chunk.js:2
Wu @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ vendors~main.55ed33fb.chunk.js:2
cu @ vendors~main.55ed33fb.chunk.js:2
Ju @ vendors~main.55ed33fb.chunk.js:2
t.hydrate @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ bundle.633ffe6e.js:1
Promise.then (async)
S @ vendors~main.55ed33fb.chunk.js:2
1345 @ bundle.633ffe6e.js:1
s @ bundle.633ffe6e.js:1
a @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
content.js:657 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
safecheck.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
The script has an unsupported MIME type ('text/html').
gtm.js?id=GTM-MNT9LL:5990 [Violation] 'setTimeout' handler took 164ms
The script has an unsupported MIME type ('text/html').
The script has an unsupported MIME type ('text/html').
pubads_impl_2021032202.js:6 Exception in queued GPT command TypeError: Cannot read property 'addService' of null
    at Arguments.<anonymous> (bundle.633ffe6e.js:1)
    at am.push (pubads_impl_2021032202.js:6)
    at sk.<anonymous> (pubads_impl_2021032202.js:6)
    at sk.push (pubads_impl_2021032202.js:6)
    at I.value (bundle.633ffe6e.js:1)
    at I.<anonymous> (bundle.633ffe6e.js:1)
    at r (catchmedia.min.js?ver=3.2.60:3)
    at Generator._invoke (catchmedia.min.js?ver=3.2.60:3)
    at Generator.e.<computed> [as next] (catchmedia.min.js?ver=3.2.60:3)
    at h (bundle.633ffe6e.js:1)
am.push @ pubads_impl_2021032202.js:6
(anonymous) @ pubads_impl_2021032202.js:6
(anonymous) @ pubads_impl_2021032202.js:6
value @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
r @ catchmedia.min.js?ver=3.2.60:3
(anonymous) @ catchmedia.min.js?ver=3.2.60:3
e.<computed> @ catchmedia.min.js?ver=3.2.60:3
h @ bundle.633ffe6e.js:1
o @ bundle.633ffe6e.js:1
Promise.then (async)
h @ bundle.633ffe6e.js:1
o @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
v @ bundle.633ffe6e.js:1
a.value @ bundle.633ffe6e.js:1
cs @ vendors~main.55ed33fb.chunk.js:2
Tu @ vendors~main.55ed33fb.chunk.js:2
t.unstable_runWithPriority @ vendors~main.55ed33fb.chunk.js:2
qo @ vendors~main.55ed33fb.chunk.js:2
bu @ vendors~main.55ed33fb.chunk.js:2
su @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ vendors~main.55ed33fb.chunk.js:2
t.unstable_runWithPriority @ vendors~main.55ed33fb.chunk.js:2
qo @ vendors~main.55ed33fb.chunk.js:2
Xo @ vendors~main.55ed33fb.chunk.js:2
Jo @ vendors~main.55ed33fb.chunk.js:2
nu @ vendors~main.55ed33fb.chunk.js:2
enqueueSetState @ vendors~main.55ed33fb.chunk.js:2
b.setState @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ bundle.633ffe6e.js:1
Promise.then (async)
(anonymous) @ bundle.633ffe6e.js:1
Promise.then (async)
value @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
Promise.then (async)
value @ bundle.633ffe6e.js:1
cs @ vendors~main.55ed33fb.chunk.js:2
Tu @ vendors~main.55ed33fb.chunk.js:2
t.unstable_runWithPriority @ vendors~main.55ed33fb.chunk.js:2
qo @ vendors~main.55ed33fb.chunk.js:2
bu @ vendors~main.55ed33fb.chunk.js:2
su @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ vendors~main.55ed33fb.chunk.js:2
t.unstable_runWithPriority @ vendors~main.55ed33fb.chunk.js:2
qo @ vendors~main.55ed33fb.chunk.js:2
Xo @ vendors~main.55ed33fb.chunk.js:2
Jo @ vendors~main.55ed33fb.chunk.js:2
nu @ vendors~main.55ed33fb.chunk.js:2
enqueueSetState @ vendors~main.55ed33fb.chunk.js:2
b.setState @ vendors~main.55ed33fb.chunk.js:2
value @ App.a0f152eb.chunk.js:1
(anonymous) @ App.a0f152eb.chunk.js:1
Promise.then (async)
value @ App.a0f152eb.chunk.js:1
(anonymous) @ App.a0f152eb.chunk.js:1
Promise.then (async)
(anonymous) @ App.a0f152eb.chunk.js:1
Promise.then (async)
value @ App.a0f152eb.chunk.js:1
value @ App.a0f152eb.chunk.js:1
cs @ vendors~main.55ed33fb.chunk.js:2
Tu @ vendors~main.55ed33fb.chunk.js:2
t.unstable_runWithPriority @ vendors~main.55ed33fb.chunk.js:2
qo @ vendors~main.55ed33fb.chunk.js:2
bu @ vendors~main.55ed33fb.chunk.js:2
su @ vendors~main.55ed33fb.chunk.js:2
nu @ vendors~main.55ed33fb.chunk.js:2
Wu @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ vendors~main.55ed33fb.chunk.js:2
cu @ vendors~main.55ed33fb.chunk.js:2
Ju @ vendors~main.55ed33fb.chunk.js:2
t.hydrate @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ bundle.633ffe6e.js:1
Promise.then (async)
S @ vendors~main.55ed33fb.chunk.js:2
1345 @ bundle.633ffe6e.js:1
s @ bundle.633ffe6e.js:1
a @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
320213562681126?v=2.9.33&r=stable:26 [Violation] 'setTimeout' handler took 50ms
The script has an unsupported MIME type ('text/html').
logituitvideoplayerlib.js?ver=3.2.60:3 [Conviva] [1617115791.722] [ERROR] [SDK] [Analytics] Client is already configured
e.<computed> @ logituitvideoplayerlib.js?ver=3.2.60:3
log @ logituitvideoplayerlib.js?ver=3.2.60:3
error @ logituitvideoplayerlib.js?ver=3.2.60:3
init @ logituitvideoplayerlib.js?ver=3.2.60:3
ConvivaAnalytic.initializeCKeyAndGatewayUrl @ logituitvideoplayerlib.js?ver=3.2.60:3
AnalyticEngine.ContentApiMetaDataInitialization @ logituitvideoplayerlib.js?ver=3.2.60:3
(anonymous) @ video-player.component.min.js?ver=3.2.60:3
(anonymous) @ video-player.component.min.js?ver=3.2.60:3
Ke @ video-player.component.min.js?ver=3.2.60:3
(anonymous) @ video-player.component.min.js?ver=3.2.60:3
Promise.then (async)
VideoplayerComponent.iniatilizePlayer @ video-player.component.min.js?ver=3.2.60:3
async function (async)
VideoplayerComponent.iniatilizePlayer @ video-player.component.min.js?ver=3.2.60:3
iniatilizePlayer @ video-player.component.min.js?ver=3.2.60:3
value @ bundle.633ffe6e.js:1
cs @ vendors~main.55ed33fb.chunk.js:2
Tu @ vendors~main.55ed33fb.chunk.js:2
t.unstable_runWithPriority @ vendors~main.55ed33fb.chunk.js:2
qo @ vendors~main.55ed33fb.chunk.js:2
bu @ vendors~main.55ed33fb.chunk.js:2
su @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ vendors~main.55ed33fb.chunk.js:2
t.unstable_runWithPriority @ vendors~main.55ed33fb.chunk.js:2
qo @ vendors~main.55ed33fb.chunk.js:2
Xo @ vendors~main.55ed33fb.chunk.js:2
Jo @ vendors~main.55ed33fb.chunk.js:2
nu @ vendors~main.55ed33fb.chunk.js:2
enqueueSetState @ vendors~main.55ed33fb.chunk.js:2
b.setState @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ bundle.633ffe6e.js:1
Promise.then (async)
(anonymous) @ bundle.633ffe6e.js:1
Promise.then (async)
value @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
Promise.then (async)
value @ bundle.633ffe6e.js:1
cs @ vendors~main.55ed33fb.chunk.js:2
Tu @ vendors~main.55ed33fb.chunk.js:2
t.unstable_runWithPriority @ vendors~main.55ed33fb.chunk.js:2
qo @ vendors~main.55ed33fb.chunk.js:2
bu @ vendors~main.55ed33fb.chunk.js:2
su @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ vendors~main.55ed33fb.chunk.js:2
t.unstable_runWithPriority @ vendors~main.55ed33fb.chunk.js:2
qo @ vendors~main.55ed33fb.chunk.js:2
Xo @ vendors~main.55ed33fb.chunk.js:2
Jo @ vendors~main.55ed33fb.chunk.js:2
nu @ vendors~main.55ed33fb.chunk.js:2
enqueueSetState @ vendors~main.55ed33fb.chunk.js:2
b.setState @ vendors~main.55ed33fb.chunk.js:2
value @ App.a0f152eb.chunk.js:1
(anonymous) @ App.a0f152eb.chunk.js:1
Promise.then (async)
value @ App.a0f152eb.chunk.js:1
(anonymous) @ App.a0f152eb.chunk.js:1
Promise.then (async)
(anonymous) @ App.a0f152eb.chunk.js:1
Promise.then (async)
value @ App.a0f152eb.chunk.js:1
value @ App.a0f152eb.chunk.js:1
cs @ vendors~main.55ed33fb.chunk.js:2
Tu @ vendors~main.55ed33fb.chunk.js:2
t.unstable_runWithPriority @ vendors~main.55ed33fb.chunk.js:2
qo @ vendors~main.55ed33fb.chunk.js:2
bu @ vendors~main.55ed33fb.chunk.js:2
su @ vendors~main.55ed33fb.chunk.js:2
nu @ vendors~main.55ed33fb.chunk.js:2
Wu @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ vendors~main.55ed33fb.chunk.js:2
cu @ vendors~main.55ed33fb.chunk.js:2
Ju @ vendors~main.55ed33fb.chunk.js:2
t.hydrate @ vendors~main.55ed33fb.chunk.js:2
(anonymous) @ bundle.633ffe6e.js:1
Promise.then (async)
S @ vendors~main.55ed33fb.chunk.js:2
1345 @ bundle.633ffe6e.js:1
s @ bundle.633ffe6e.js:1
a @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
(anonymous) @ bundle.633ffe6e.js:1
logituitvideoplayerlib.js?ver=3.2.60:3 [Violation] 'setTimeout' handler took 52ms
vendors~main.55ed33fb.chunk.js:2 [Violation] 'setTimeout' handler took 117ms
logituitvideoplayerlib.js?ver=3.2.60:3 [Violation] 'setTimeout' handler took 67ms
eme_interception.js:348 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior.
(anonymous) @ eme_interception.js:348
(anonymous) @ eme_interception.js:103
(anonymous) @ logituitvideoplayerlib.js?ver=3.2.60:3
e @ logituitvideoplayerlib.js?ver=3.2.60:3
(anonymous) @ logituitvideoplayerlib.js?ver=3.2.60:3
Promise.catch (async)
(anonymous) @ logituitvideoplayerlib.js?ver=3.2.60:3
e @ logituitvideoplayerlib.js?ver=3.2.60:3
requestKeySystemAccess @ logituitvideoplayerlib.js?ver=3.2.60:3
(anonymous) @ logituitvideoplayerlib.js?ver=3.2.60:3
D @ logituitvideoplayerlib.js?ver=3.2.60:3
initializeForMedia @ logituitvideoplayerlib.js?ver=3.2.60:3
de @ logituitvideoplayerlib.js?ver=3.2.60:3
(anonymous) @ logituitvideoplayerlib.js?ver=3.2.60:3
activate @ logituitvideoplayerlib.js?ver=3.2.60:3
ve @ logituitvideoplayerlib.js?ver=3.2.60:3
o @ logituitvideoplayerlib.js?ver=3.2.60:3
eme_interception.js:348 It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior.
(anonymous) @ eme_interception.js:348
(anonymous) @ eme_interception.js:103
(anonymous) @ logituitvideoplayerlib.js?ver=3.2.60:3
e @ logituitvideoplayerlib.js?ver=3.2.60:3
requestKeySystemAccess @ logituitvideoplayerlib.js?ver=3.2.60:3
D @ logituitvideoplayerlib.js?ver=3.2.60:3
M @ logituitvideoplayerlib.js?ver=3.2.60:3
(anonymous) @ logituitvideoplayerlib.js?ver=3.2.60:3
trigger @ logituitvideoplayerlib.js?ver=3.2.60:3
handleEvent @ logituitvideoplayerlib.js?ver=3.2.60:3



This issue showing on sonyliv.com  in console..but others sites working fine..

**Comment by Suyashjain05** [comment]
@tomer8007 any solution to this? 🤔

**Comment by tvserial** [comment]
not working..

**Comment by sahilkundu** [comment]
This is also give me error like that **it is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior**
![screenshot](https://user-images.githubusercontent.com/71582663/113407121-55608d80-93ca-11eb-9861-4bfc497c046e.png)
**

**Comment by sahilkundu** [comment]
> I tried to silence this warning before in `addRobustnessLevelIfNeeded` (eme_interception.js), but I don't think it should matter too much. You can try to debug it to see if you get license requests or respones.

Bro how it is can fix give some details
