### ISSUE TITLE
Will this be updated in the future?

### ISSUE THREAD

**Issue by etnaddcok** [tomer8007/widevine-l3-decryptor#52]
today it seems that it no longer works, until yesterday it worked well, in the future will it come back?

**Comment by HawkLiking** [comment]
If you do not see this error, it still works
```
Can't verify license request signature; either the platform is wrong or the key has changed!
```

So I confirm it still works, you can check by yourself here https://bitmovin.com/demos/drm

**Comment by etnaddcok** [comment]
> On which website ?
> 
> If you do not see this error, that means it still works :
> 
> ```
> Can't verify license request signature; either the platform is wrong or the key has changed!
> ```
> 
> So I confirm it still works, you can check by yourself here https://bitmovin.com/demos/drm

yes bro that is the message that shows me until yesterday it worked fine today that poster already appears

**Comment by HawkLiking** [comment]
> yes bro that is the message that shows me until yesterday it worked fine today that poster already appears

Have you at least tested on https://bitmovin.com/demos/drm with Chrome 88 ?

**Comment by etnaddcok** [comment]
Look here, bro, I wanted to get the audio, can you see if you have more luck? https://watch.boomerang.com/watch/38/13

**Comment by etnaddcok** [comment]
> Have you at least tested on https://bitmovin.com/demos/drm with Chrome 88 ?

Look here, bro, I wanted to get the audio, can you see if you have more luck? https://watch.boomerang.com/watch/38/13
