### ISSUE TITLE
ON SHIFT72 SYSTEM no longer works

### ISSUE THREAD

**Issue by ningsibuqu** [tomer8007/widevine-l3-decryptor#53]
![L $PU0CVZECFXHM JWHNO24](https://user-images.githubusercontent.com/51028975/113393692-9d32e500-93c9-11eb-83eb-fb4b5e7cec42.png)

They force the Edge and can identify if it is an older version of wv

![image](https://user-images.githubusercontent.com/51028975/113393970-04e93000-93ca-11eb-9575-de258511d95a.png)

Now can only be played under 4.10.2209
![J(3~M XNKS`)GT7F1CJ$1E](https://user-images.githubusercontent.com/51028975/113394149-51347000-93ca-11eb-8b1f-4fb3a13e9fc6.png)

**Comment by tomer8007** [comment]
Impressive.

**Comment by S-hdyn** [comment]
But Edge v88 still works which was based from chromium🤔
