### ISSUE TITLE
Error in this extension

### ISSUE THREAD

**Issue by sahilkundu** [tomer8007/widevine-l3-decryptor#54]
Hey this repository give an error like that " **It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior**.  Pleases give any solution.
![screenshot](https://user-images.githubusercontent.com/71582663/113405985-51337080-93c8-11eb-91e7-aa56af5a3d5b.png)

**Comment by HawkLiking** [comment]
Duplicated https://github.com/tomer8007/widevine-l3-decryptor/issues/50
