### ISSUE TITLE
When can we expect a White paper on your approach?

### ISSUE THREAD

**Issue by Ashish0804** [tomer8007/widevine-l3-decryptor#56]
This was a very promising and nice proof of work. When can we expect a whitepaper on it from you?

Thanks.

**Comment by tomer8007** [comment]
Hopefully it'll happen when I'll make sure that the new CDM is different enough, so that posting it won't really help find the newer key.

**Comment by HawkLiking** [comment]
@tomer8007 I'm quite sure that the new CDM is different enough. Because if is wasn't, that would mean that Google doesn't *really* want to prevent this to happen again 😅 and they don't want to...

So I can't wait to read your paper!

**Comment by megapro17** [comment]
> that posting it won't really help find the newer key.

You're really retarded

**Comment by Sipherdrakon** [comment]
> > that posting it won't really help find the newer key.
> 
> You're really retarded

So he's retarded because he doesn't want DRM to become even harder if the new CDM gets broken and released to the public? Yeah okay, way to use that big brain of yours. :-P

**Comment by gareth41** [comment]
> Hopefully it'll happen when I'll make sure that the new CDM is different enough, so that posting it won't really help find the newer key.

Sounds like you’re working for them now, or you’ve had to sign a non disclosure agreement before they paid you a bounty.

**Comment by hikomo22** [comment]
I can teach you how to get the keys from the streams.
I will tell the price by mail
contact me
natsume.hibari.19@gmail.com

by the way tomer8007 has always worked with microsoft

**Comment by megapro17** [comment]
> I can teach you how to get the keys from the streams.
> I will tell the price by mail
> contact me
> [natsume.hibari.19@gmail.com](mailto:natsume.hibari.19@gmail.com)
> 
> by the way tomer8007 has always worked with microsoft

I can give you 0.99$. Deal?

**Comment by gareth41** [comment]
I don’t need the keys, my entertainment is right here

**Comment by cookies-f-json** [comment]
If anybody wants some content keys, contact: hopeless#3338 Discord.

**Comment by megapro17** [comment]
> If anybody wants some content keys, contact: hopeless#3338 Discord.

**DON'T GIVE ANY MONEY TO THIS PERSON, ANOTHER SCAMMER WITHOUT ANY PROOFS**

**Comment by cookies-f-json** [comment]
> 
> 
> > If anybody wants some content keys, contact: hopeless#3338 Discord.
> 
> **DON'T GIVE ANY MONEY TO THIS PERSON, ANOTHER SCAMMER WITHOUT ANY PROOFS**

I'm not even asking for any money. You don't have to do ALL CAPS, relax. If someone is in desperate need of content keys, they can contact.

**Comment by gareth41** [comment]
This thread is my daily source of entertainment.
