### ISSUE TITLE
Request: PlayReady DRM decryptor

### ISSUE THREAD

**Issue by proall** [tomer8007/widevine-l3-decryptor#60]
Hey,
Do you have any decryptor tool for PlayReady DRM protection?
I'm trying to rip from Netflix AVC codec thats mean the Main Profile, with WideVine L3 Netflix offers only the High Profile
Main: 5800kbps of bitrate
High: 1180kbps of bitrate

I success to download 1 main but not protected one with Edge, plz if you can help me i will pay money.

**Comment by tomer8007** [comment]
No

**Comment by HackerBoy0412** [comment]
Its still work, just dont use Edge.

**Comment by p2mgrup** [comment]
@HackerBoy0412, could you tell how you are downloading from main profile?

**Comment by proall** [comment]
Its work but without AVC codec xD @HackerBoy0412

**Comment by HackerBoy0412** [comment]
ok, but it have nothing todo with the decryptor
