### ISSUE TITLE
Further Support?

### ISSUE THREAD

**Issue by WHTJEON** [tomer8007/widevine-l3-decryptor#61]
Are you going to release a new update after old CDMs get revoked on May 31? Or are you just going to archive this repository with no further support?

**Comment by tomer8007** [comment]
No, this is not going to get updated to support newer CDMs.

**Comment by nickcartery** [comment]
> No, this is not going to get updated to support newer CDMs.

Can you write a guide how you can leak the RSA private key in the old CDM?

**Comment by tomer8007** [comment]
This was already answered in other issues. I don't want the new key to get extracted, so maybe.
