### ISSUE TITLE
Widevine l3 RSA Key

### ISSUE THREAD

**Issue by proall** [tomer8007/widevine-l3-decryptor#62]
If i will keep (widevinecdm.dll), it will work forever?
Or when google will change the key it will be broke?

**Comment by HawkLiking** [comment]
Old CDMs won't work anymore.

see https://github.com/tomer8007/widevine-l3-decryptor/issues/55#issuecomment-814662633

**Comment by proall** [comment]
Oh,
But there is a method to get the new RSA private key?

**Comment by HawkLiking** [comment]
Currently there is no way to get the new RSA private key. Reversing the CDM is not an easy thing.

The owner of this repo will not update this project even if he find the new key ( https://github.com/tomer8007/widevine-l3-decryptor/issues/61#issuecomment-825567458 ), but he maybe will publish a white paper if it won't help to find the new key ( https://github.com/tomer8007/widevine-l3-decryptor/issues/56#issuecomment-817108655 )

**Comment by proall** [comment]
What is the WhitePaper?
And how it will help me to find the new RSA Priv key?

**Comment by HawkLiking** [comment]
Just read this issue: https://github.com/tomer8007/widevine-l3-decryptor/issues/56
### **You won't be able to find the new private key.**
