### ISSUE TITLE
Priv key

### ISSUE THREAD

**Issue by proall** [tomer8007/widevine-l3-decryptor#65]
It will be really the end?
on 31 may, google will change the key?
and if someone or you tomer can publish the key?

i'm really need that key i will pay money for that..

**Comment by proall** [comment]
tomer8007, if you want sell the the new key content me on telegram,
@UriUKN

**Comment by Nintendocustom** [comment]
Yes, it's going to end, just read the following issue: #55 
I don't think anyone will just give you the new private key.

**Comment by astravaganza** [comment]
> tomer8007, if you want sell the the new key content me on telegram,
> @UriUKN

No one would do that, already too dangerous to let these things out.

**Comment by parnexcodes** [comment]
I hope you understand that he made this to show google their protection is weak not to help people for doing webdl's.

**Comment by Nintendocustom** [comment]
Software based DRM is always weak.
