### ISSUE TITLE
❌ ChromeCDM 1610 (13701) has been revoked

### ISSUE THREAD

**Issue by moonmuaaz000** [tomer8007/widevine-l3-decryptor#67]
this will go in history.

**Comment by astravaganza** [comment]
lmao

**Comment by proall** [comment]
sad for you.

**Comment by bottasbacsi** [comment]
thanks legend

**Comment by moonmuaaz000** [comment]
> sad for you.

Who said me I have other keys

**Comment by D00oo00M** [comment]
> > sad for you.
> 
> Who said me I have other keys

did you have an alternative that you can send?

**Comment by detodotv** [comment]
> > sad for you.
> 
> Who said me I have other keys

how can i send you a message?
