### ISSUE TITLE
Doesn't work for some sites any more... But if some one can make a little change in the extension I really think it would be able to easily work this around!

### ISSUE THREAD

**Issue by mirrorx2** [tomer8007/widevine-l3-decryptor#68]
> [sd.zip](https://github.com/tomer8007/widevine-l3-decryptor/files/6480210/sd.zip)
> here are old versoin of widevinecdm.dll and widevinecdm.dll.sig

> Sorry, a new key will not be published (this is just getting into a cat-and-mouse game).
> 
> If you really want a workaround, though, you can just replace your `widevinecdm.dll` and `widevinecdm.dll.sig` files with the older versions.

I have a site which I want to take a video.....The extension worked fine until yesterday...I used chrome version 87. But today widevine decrypter didn't capture the keys and chrome version hasn't been updated too.... I tried many old versions older than version 87 today but none of it worked! Then when I again switched to version 87 there comes a message when playing the videos saying "update your windows to latest version"... I tried replacing widevinecdm.dll and widevinecdm.dll.sig with older versions too but none of it worked...

What I have to ask is if you know any other way to get the keys please help me...I really need some videos...They are lesson videos and I really need to get them before they expire😭... Also I can give you a link if anyone wants to try....If anyone here who  read this have solution please can you be kind and share it 🙏 Thank you.

**Comment by proall** [comment]
Widevine has been update for a newer RSA Private Key, if you don't know how
to extract the key, i can't decrypt videos anymore, and the owner of this project
too not going to leak again the key, so sad for you and for a lot of ppls here.

**Comment by astravaganza** [comment]
Leave it. No one is doing a new key extraction. WEBRip is your best option.
