### ISSUE TITLE
Widevine CDM Version

### ISSUE THREAD

**Issue by inntremux** [tomer8007/widevine-l3-decryptor#7]
From which Widevine Content Decryption Module (widevinecdm.dll) version is key?
Because Google recenty push new version of Desktop L3 CDM for Windows/Linux

**Comment by tomer8007** [comment]
Original research was done on `widevinecdm.dll` 4.10.1610.0

**Comment by athrowaway-2020** [comment]
The newest version of the ChromeCDM for Windows, 1679, shares its device certificate with 1610, so the private key in this repo can be used with newest version of the CDM library you have installed, for now.

**Comment by YssDiamond** [comment]
Rip it does not work anymore

**Comment by inntremux** [comment]
> The newest version of the ChromeCDM for Windows, 1679, shares its device certificate with 1610, so the private key in this repo can be used with newest version of the CDM library you have installed, for now.

I've checked that too, dll has pub key in it so they share the same priv key

**Comment by inntremux** [comment]
This is my Discord server dedicated to this repo, if it get DMCA (and he will soon) so feel free to join @tomer8007 and any other interested
https://discord.gg/vWC2Zm

**Comment by stinkteeth** [comment]
> Original research was done on `widevinecdm.dll` 4.10.1610.0

What's the method to extract the keybox from the dll?

**Comment by inntremux** [comment]
> > Original research was done on `widevinecdm.dll` 4.10.1610.0
> 
> What's the method to extract the keybox from the dll?

I don't think that keybox can be extracted from dll (if any), only private key, @tomer8007 correct me if i'm wrong?

**Comment by stinkteeth** [comment]
> I don't think that keybox can be extracted from dll (if any), only private key, @tomer8007 correct me if i'm wrong?

Of course you're correct.

One of the old python tools included keyextractor.py, which could extract the private key from the browser dll. It stopped working around 1.4.8.984. I assumed the means by which the key is stored in the dll had changed. It couldn't have changed all that much though, right?

**Comment by kokozaurz** [comment]
> > I don't think that keybox can be extracted from dll (if any), only private key, @tomer8007 correct me if i'm wrong?
> 
> Of course you're correct.
> 
> One of the old python tools included keyextractor.py, which could extract the private key from the browser dll. It stopped working around 1.4.8.984. I assumed the means by which the key is stored in the dll had changed. It couldn't have changed all that much though, right?

from some research it looks like that after that version they introduced obfuscation. 

Curious not only how to extract the private key but also **device_client_id_blob**

**Comment by inntremux** [comment]
> > > I don't think that keybox can be extracted from dll (if any), only private key, @tomer8007 correct me if i'm wrong?
> > 
> > 
> > Of course you're correct.
> > One of the old python tools included keyextractor.py, which could extract the private key from the browser dll. It stopped working around 1.4.8.984. I assumed the means by which the key is stored in the dll had changed. It couldn't have changed all that much though, right?
> 
> from some research it looks like that after that version they introduced obfuscation.
> 
> Curious not only how to extract the private key but also **device_client_id_blob**

I just did it 😃

**Comment by stinkteeth** [comment]
> Curious not only how to extract the private key but also **device_client_id_blob**

The blob isn't included with this extension, is it?

It was at least a few years ago, so my memory is fuzzy, but I remember the blob being easier and perhaps not even needing to be extracted.

**Comment by kokozaurz** [comment]
> > > > I don't think that keybox can be extracted from dll (if any), only private key, @tomer8007 correct me if i'm wrong?
> > > 
> > > 
> > > Of course you're correct.
> > > One of the old python tools included keyextractor.py, which could extract the private key from the browser dll. It stopped working around 1.4.8.984. I assumed the means by which the key is stored in the dll had changed. It couldn't have changed all that much though, right?
> > 
> > 
> > from some research it looks like that after that version they introduced obfuscation.
> > Curious not only how to extract the private key but also **device_client_id_blob**
> 
> I just did it 😃

care to share details? :)

**Comment by inntremux** [comment]
> > > > > I don't think that keybox can be extracted from dll (if any), only private key, @tomer8007 correct me if i'm wrong?
> > > > 
> > > > 
> > > > Of course you're correct.
> > > > One of the old python tools included keyextractor.py, which could extract the private key from the browser dll. It stopped working around 1.4.8.984. I assumed the means by which the key is stored in the dll had changed. It couldn't have changed all that much though, right?
> > > 
> > > 
> > > from some research it looks like that after that version they introduced obfuscation.
> > > Curious not only how to extract the private key but also **device_client_id_blob**
> > 
> > 
> > I just did it 😃
> 
> care to share details? :)

Maybe on discord

**Comment by vhvvx777** [comment]
Guys and how to contact the author. There is one site where the expansion cannot intercept the key, since video links are created in a dynamic window. Maybe the author knows how to fix it

**Comment by steamgirl2020** [comment]
> 这是我专用于此仓库的Discord服务器，如果它获得DMCA（他很快就会），请随时加入@ tomer8007和任何其他感兴趣的
> https://discord.gg/vWC2Zm

Invalid invitation？

**Comment by inntremux** [comment]
Here is permanent invitation:
https://discord.gg/ryh9xqA

**Comment by vhvvx777** [comment]
In russia there is a site https://hd.kinopoisk.ru/, due to the creation of dynamic pages, the extension does not see the key to the video. Is it possible to fix this somehow?

> Original research was done on `widevinecdm.dll` 4.10.1610.0

**Comment by Omkar47** [comment]
@inntremux Can i get the invite?

**Comment by Nintendocustom** [comment]
> > > I don't think that keybox can be extracted from dll (if any), only private key, @tomer8007 correct me if i'm wrong?
> > 
> > 
> > Of course you're correct.
> > One of the old python tools included keyextractor.py, which could extract the private key from the browser dll. It stopped working around 1.4.8.984. I assumed the means by which the key is stored in the dll had changed. It couldn't have changed all that much though, right?
> 
> from some research it looks like that after that version they introduced obfuscation.
> 
> Curious not only how to extract the private key but also **device_client_id_blob**

I would like know this too! Is there any way to contact someone who can help me with this?

**Comment by Brhsoftco** [comment]
Discord anyone?

**Comment by billyriantono** [comment]
new discord anyone ? @inntremux

**Comment by cimbor** [comment]
Hi, I want to extract some keys for live content with this addon but unfortunately I have no keys in console, I also tried with a custom license proxy and pywidevine but I get error as response; the proxy is working fine on Android players live exostreamr and bitmovin. Anyone willing to help/exchange ideas?

**Comment by CriminalMAD** [comment]
@inntremux can you post new invite link?

**Comment by astravaganza** [comment]
> @inntremux can you post new invite link?

Kindly share here too, I'm in dire need of the blob file

**Comment by abderrahmanesaad** [comment]
plz share as discord invitation
