### ISSUE TITLE
I can teach you how to get the keys from the streams.

### ISSUE THREAD

**Issue by mirrorx2** [tomer8007/widevine-l3-decryptor#72]
I can teach you how to get the keys from the streams.
I will tell the price by mail
contact me
natsume.hibari.19@gmail.com

by the way tomer8007 has always worked with microsoft

_Originally posted by @hikomo22 in https://github.com/tomer8007/widevine-l3-decryptor/issues/56#issuecomment-855310719_

**Comment by hikomo22** [comment]
sorry first you must pay 30 us later you will see my screen
