### ISSUE TITLE
Vendo Chrome 2209 L3 funcionando por 200 GBP

### ISSUE THREAD

**Issue by cromo2209** [tomer8007/widevine-l3-decryptor#73]
![4cfadb88103e78c7c158c585628e7ff0](https://user-images.githubusercontent.com/77932667/121034765-e7ba4e80-c7ca-11eb-8f0a-6323889ba148.png)

trabajando con amazon hasta 1080p, netflix y más
precio :- 200 GBP
pago solo por btc
Entrega por correo electrónico automáticamente después del pago de coinbase

https://commerce.coinbase.com/checkout/d5bfac19-e8fd-4684-8d8a-503143320e76

**Comment by WHTJEON** [comment]
Is this guy seriously trying to sell a CDM file which can be extracted by anyone for 300 dollars? Shit
