### ISSUE TITLE
Will it be updated?

### ISSUE THREAD

**Issue by wyg520** [tomer8007/widevine-l3-decryptor#76]
Will it be updated?
It can't be used after June 1.
thanks.

**Comment by manifesto1** [comment]
NO

**Comment by tomer8007** [comment]
Doing so is probably just going to make Google revoke the CDM again, or worse.

**Comment by loveyoursupport** [comment]
Btw 2209 will also revoke when its time come , so why you worry much about it @tomer8007

**Comment by Zachary24** [comment]
@tomer8007 is there any way to force a (widevine based) webplayer to use a certain stream from the MPD file?
After CBS moved to Paramount Plus the Big brother life feeds go to like 360p constantly, have no problems streaming any other content except for the live feeds (buffering does also happen when going back through the feeds). just curious if theres any way to force it to only play the highest quality one.
