### ISSUE TITLE
Got the key but can't decrypt unknown extension file

### ISSUE THREAD

**Issue by zackmark29** [tomer8007/widevine-l3-decryptor#8]
This is great extension.
I got the key from the log, and then I tried to download single video stream like this:

https://amssabscbn.akamaized.net/3f2143a8-bcec-42fd-8e01-1d80f409f064/gbl_malaya-1_IM-.ism/QualityLevels(128000)/Fragments(audioname=60160000,format=mpd-time-csf)

When I tried to decrypt it with ffmpeg, I'm getting this error:

[mov,mp4,m4a,3gp,3g2,mj2 @ 0000016bc42b8e00] could not find corresponding trex (id 1)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000016bc42b8e00] could not find corresponding track id 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000016bc42b8e00] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000016bc42b8e00] error reading header
TEST: Invalid data found when processing input

Here's the mpd content:
https://anonfiles.com/N9023ei6pa/manifest_format_mpd-time-csf_filter_b2200_mpd

**Comment by athrowaway-2020** [comment]
First off, this is just a single fragment of the stream. You can't decrypt it without having the init segment.
Secondly, this isn't even the video stream, this is a segment of the audio stream, make sure you're downloading the right stream and are using the right key for it.
Lastly, this isn't an issue with this extension, it's working fine since you did get the key; if you are unable to download a track correctly, ask for support elsewhere, such as the Discord server linked in a previous issue.

**Comment by zackmark29** [comment]
> First off, this is just a single fragment of the stream. You can't decrypt it without having the init segment.
> Secondly, this isn't even the video stream, this is a segment of the audio stream, make sure you're downloading the right stream and are using the right key for it.
> Lastly, this isn't an issue with this extension, it's working fine since you did get the key; if you are unable to download a track correctly, ask for support elsewhere, such as the Discord server linked in a previous issue.

Oh I see. thank you for the information. I didn't know that it needs the initial.
I'll try to figure out the right stream

Thank you. and the discord is already expired

**Comment by kaka-decryptor** [comment]
Great Job mate , i have been tested is work as well , but on my platform just i got keys decrypt then open segments as well, i will try make a script over windows to reponse automatic to linux for decrypt segments after download and restream them as well .
Alot thx for Tomer8007, it is nice work . :+1:

**Comment by zackmark29** [comment]
> Great Job mate , i have been tested is work as well , but on my platform just i got keys decrypt then open segments as well, i will try make a script over windows to reponse automatic to linux for decrypt segments after download and restream them as well .
> Alot thx for Tomer8007, it is nice work . 👍

Actually I found another ydl fork which can download the ism file
https://github.com/nyuszika7h/youtube-dl/tree/drm
